### PR TITLE
feat(css): Add CSS and WebKit scrollbar specifications

### PR DESCRIPTION
**Pull request by ExE-Boss**
Both @erikadoyle and @jpmedley have confirmed the&nbsp;**Microsoft&nbsp;Edge** and&nbsp;**Google&nbsp;Chrome** statuses respectively in&nbsp;https://github.com/mdn/browser-compat-data/pull/2424#issuecomment-405392042 and https://github.com/mdn/browser-compat-data/pull/2424#issuecomment-405645225.

---

review?(@alrra)

### CODE REVIEW

**Comment by alrra** [comment]
Cc: @FremyCompany @gregwhitworth

**Comment by FremyCompany** [comment]
The spec linked by @ExE-Boss and the description he gives it are not correct. The latest version of the spec has `scrollbar-color: auto | light | dark` and `scrollbar-width: auto | thin | none` and it is currently too early to signify either support or no support for the feature as the spec hasn't finished maturing yet. I recommend not merging this PR.

**Comment by FremyCompany** [comment]
The second part of the PR is however accurate, we could merge that:
```
  { 
    "name": "WebKit Scrollbars", 
    "category": "CSS", 
    "summary": "The ::-webkit-scrollbar CSS pseudo-element affects the style of the scrollbar of an element.", 
    "standardStatus": "De-facto standard", 
    "ieStatus": { 
      "text": "Under Consideration", 
      "priority": "Medium" 
    }, 
    "ff_views": { 
      "text": "In Development" 
    }, 
    "impl_status_chrome": "Shipped", 
    "uservoiceid": 9081910, 
    "statusid": 333 
  }
```

**Comment by alrra** [comment]
Thanks, @FremyCompany!

**Comment by alrra** [comment]
> The second part of the PR is however accurate, we could merge that:

Done! Thanks, @ExE-Boss!

**Comment by SelenIT** [comment]
@FremyCompany, are you sure that it’s correct to say that *WebKit* scrollbars styling is in development in Firefox? I understand the current Firefox status as they are implementing the newly proposed spec, which is mostly developed by the same people who implement it, *instead* of the WebKit’s pseudo-element-based approach.

**Comment by FremyCompany** [comment]
@SelenIT Ah, yes, sorry, I didn't catch that. I'll fix it.

**Pull request closed without merging**
