### PR TITLE
Link to the new EdgeHTML issue tracker

### PR DESCRIPTION
**Pull request by alrra**
Note: httpS://issues.microsoftedge.com/ doesn't seem to work (this may be related to: https://github.com/MicrosoftEdge/Status/issues/346?).

``` bash
$ curl -sSIL https://issues.microsoftedge.com/
curl: (28) Connection timed out after 60001 milliseconds
```

Maybe link to https://developer.microsoft.com/microsoft-edge/platform/issues/?

### CODE REVIEW

**Comment by alrra** [comment]
> httpS://issues.microsoftedge.com/ doesn't seem to work :(

Maybe link to https://developer.microsoft.com/microsoft-edge/platform/issues/ ?

**Comment by molant** [comment]
Yes, @kypflug is working on that but the certificates only get updated every few months...

**Comment by alrra** [comment]
> Yes, @kypflug is working on that but the certificates only get updated every few months...

@molant Should I update my commit to link to https://developer.microsoft.com/microsoft-edge/platform/issues/ until that is solved?

**Comment by molant** [comment]
@alrra yes, let's update to the final url so we avoid more redirects. Thanks!

**Comment by alrra** [comment]
@molant Done!

**Comment by molant** [comment]
Thanks!

**Pull request merged**
