### PR TITLE
Added statusid to every status item for bringing status info into VSO

### PR DESCRIPTION
**Pull request by gregwhitworth**
The diff looks scarier than it actually is. Basically, I added in a property with the name of `statusid` for linking status to VSO. I also updated the readme to mention that a `statusid` should exist and also incremented.

@molant I was going to try and render Status with this new JSON set but the site seems to be pulling from the API, thus going the fiddler route to test and ensure this is correctly setup isn't going to work. If you can point me to how to test the entire json file, I'll do so.

### CODE REVIEW

**Comment by alrra** [comment]
@gregwhitworth You will also need to update the [schema](https://github.com/MicrosoftEdge/Status/blob/e766ee264761a21a1357315c4663583f5f8b291a/scripts/schema.json).

**Comment by gregwhitworth** [comment]
@alrra Thanks - just added it and made it required - out of curiosity is the schema for Travis?

**Comment by molant** [comment]
@gregwhitworth we use it on Travis and also in the site to validate the data is coming is OK

**Comment by gregwhitworth** [comment]
@molant and @alrra I updated WebGL, also added in statusid for the newer items so that we can get this completed. Please review when you get a chance.

**Comment by alrra** [comment]
@gregwhitworth There are some conflicts, can you fix them? Thanks!

**Comment by gregwhitworth** [comment]
@alrra I must be missing it because git says it's all up to date and searching the local repo for conflicts (I'm doing it the super effective way of looking for `<<<`).

**Comment by molant** [comment]
@gregwhitworth I think you need to rebase the latest changes from master into your PR.

**Comment by gregwhitworth** [comment]
@molant I apologize for my ignorance but I'm confused as my `status.json` is up to date with master as I merged them in today under this commit before requesting review (https://github.com/MicrosoftEdge/Status/pull/587/commits/438a646f952537030c85c9cb714039922f8ecbca). So I'll need a bit more guidance in what specifically rebasing will accomplish (are you wanting a specific flag passed). And as I noted above, trying to fetch from upstream yields git stating "Up to date".

Again, sorry to be difficult I'm just at a loss at what to do.

**Comment by alrra** [comment]
@gregwhitworth I took care of it. 

Come by my office next week and I will explain.

Thanks!

**Comment by gregwhitworth** [comment]
@alrra Thanks - I defiantly will.

**Pull request closed without merging**
