### PR TITLE
Beacon status to preview release

### PR DESCRIPTION
**Pull request by ghost**
Beacon is enabled by default in 14342. https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/14342/

### CODE REVIEW

**Comment by NoNameProvided** [comment]
Preview Release means the feature is behind a flag, but this is finalized if I understand correctly so it should have the status of `Shipped`.

**Comment by mkurz** [comment]
+1 for "Shipped"

**Comment by molant** [comment]
IIRC we use shipped only when it is in the stable release. Right now it is only on insiders so it should be in preview.

**Comment by NoNameProvided** [comment]
Ahh thats true, I am an insider but it's so stable that sometimes I just forget that it's an insider version.

**Comment by jacobrossi** [comment]
Yep, Preview Release is the right call here. And @NoNameProvided glad to hear it's a good build. ;-) 

Thanks @nextPrime

**Pull request merged**
