### PR TITLE
Use Chrome ID for WOFF2: Fix #369

### LINKED ISSUE #369: WOFF2 supported by Firefox since v39
WOFF2 support for Firefox is still set to "Under development" here
https://dev.windows.com/en-us/microsoft-edge/platform/status/?filter=f3f0000bf&search=woff%20file

but in the linked bug tracker it says that it was in the relnotes for v35:
https://bugzilla.mozilla.org/show_bug.cgi?id=1064737#c12

apparently turned on by default in v39:
https://developer.mozilla.org/en-US/Firefox/Releases/39

### PR DESCRIPTION
**Pull request by ghost**
Let's use the Chrome Status' tracking data for WOFF 2.0, which is accurate. https://www.chromestatus.com/features/6718644721549312

### CODE REVIEW

**Comment by jacobrossi** [comment]
:+1:  Thanks again, @nextPrime!

**Comment by ghost** [comment]
@jacobrossi No problem! But the patch is not merged?

**Comment by jacobrossi** [comment]
Weird, swear I pressed  the button haha. Thanks!

**Comment by jacobrossi** [comment]
Sware=swear

**Pull request merged**
