### PR TITLE
Changing status of sticky to in development

### PR DESCRIPTION
**Pull request by gregwhitworth**

### CODE REVIEW

**Comment by auchenberg** [comment]
Can I tweet this, @gregwhitworth ?

**Comment by gregwhitworth** [comment]
@auchenberg lol - that was fast :) I'd let @kypflug make that call, but we should probably tweet from MSEdgeDev. Pinging @molant so he can merge it :) Also a cc to @jacobrossi since Kyle may still be oof.

**Comment by auchenberg** [comment]
@gregwhitworth  Hah, what else to do one the weekend, right? 😄

**Comment by gregwhitworth** [comment]
Thanks @alrra :)

**Comment by mkurz** [comment]
This is really awesome!
Please don't forget to make css sticky work on table headers (other browsers had issues with that).

If you could also add support for the form attribute now as well Edge would rock even more :smile:

**Comment by gregwhitworth** [comment]
@mkurz thanks for reaching out - testing out this [fiddle ](https://jsfiddle.net/hr5dktah/1/)- it doesn't seem to work in FF/Chrome (latest canary of each). I also tried applying it to the `tr` of the `thead`. While duplicating the same overall layout using flex, it works - see this [fiddle](https://jsfiddle.net/jh5f90yp/1/). Maybe I'm missing something here though.

**Comment by mkurz** [comment]
@gregwhitworth In Chrome stable 57.0.2987.110 (64-bit) on Ubuntu 16.04 the first fiddle (the one without flex) is working for me.

**Comment by gregwhitworth** [comment]
Ahhh, you're right it does work on Stable - it doesn't on Canary 59.0.3045. Also can you test out Firefox on Linux?

**Comment by gregwhitworth** [comment]
@mkurz filed a [bug ](https://bugs.chromium.org/p/chromium/issues/detail?id=702927&q=sticky&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) on them in hopes they don't ship this to stable

**Comment by mkurz** [comment]
@gregwhitworth In Firefox 52.0 on the same Ubuntu machine it's **not** working.

**Comment by gregwhitworth** [comment]
@mkurz thanks for the info

**Comment by mkurz** [comment]
@gregwhitworth I found the Firefox issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=975644

**Comment by mkurz** [comment]
It's listed under "Known issues" in http://caniuse.com/#feat=css-sticky

**Comment by ctolkien** [comment]
Hurrah!

**Comment by mkurz** [comment]
@gregwhitworth If you don't know yet, position sticky on `<thead>` and `<tr>` was intentionally disabled by the Chrome team - see [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=673538#c20) and [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=695179). That's why it is working in Chrome stable but not in Canary.

**Pull request closed without merging**
