### PR TITLE
Add data for CSS resize

### PR DESCRIPTION
**Pull request by am11**
Fix: #68

### CODE REVIEW

**Comment by am11** [comment]
@alrra, PTAL. :)

**Comment by alrra** [comment]
Woohoo! Thanks, @am11!

---

ping @gregwhitworth ⬆️

**Comment by gregwhitworth** [comment]
Can you make this Under Consideration rather than not currently planned at a pri of low currently. Thanks,

**Comment by am11** [comment]
@gregwhitworth, addressed the feedback. :)
And I am very glad to know that it is already under consideration! 👍

**Comment by molant** [comment]
@am11 @alrra @gregwhitworth isn't there an entry in chromestatus for this features? I've look but haven't found anything :/

**Comment by am11** [comment]
@molant, I got a hit on this page: https://www.chromestatus.com/metrics/css/popularity (search for `resize` and `outline-offset`).

**Comment by alrra** [comment]
> isn't there an entry in chromestatus for this features? 

@molant It doesn't seem so.

**Comment by alrra** [comment]
Thanks, @am11! 💜

**Pull request closed without merging**
