### PR TITLE
Add three chromestatus.com ids to same status.microsoftedge.com features

### PR DESCRIPTION
**Pull request by mdittmer**
For verification: Name (URL)

Edge feature: Public Key Pinning Extension for HTTP (https://developer.microsoft.com/en-us/microsoft-edge/platform/status/publickeypinningextensionforhttp)
Chrome feature: HTTP Public Key Pinning violating reporting (https://www.chromestatus.com/feature/4669935557017600)

Edge feature: Modules (ES6) (https://developer.microsoft.com/en-us/microsoft-edge/platform/status/moduleses)
Chrome feature: Modules (ES6) : 1 (https://www.chromestatus.com/feature/5365692190687232) 

Edge feature: ASM.js (https://developer.microsoft.com/en-us/microsoft-edge/platform/status/asmjs)
Chrome feature: asm.js (https://www.chromestatus.com/feature/5053365658583040)

### CODE REVIEW

**Comment by RByers** [comment]
For context: https://github.com/GoogleChrome/chromium-dashboard/issues/114.  /cc @jacobrossi 
I expect we'll have some more of these.

**Comment by jacobrossi** [comment]
Awesome!  

For ASM.js, is this a full implementation that includes ahead-of-time compilation and type specialized compilation without bailouts?  In the past, I think V8 had said they would "recognize" ASM compliant code and make compiler optimizations to make it run faster, but not do AOT etc. Super awesome if it's the full meal deal now!

/cc @bterlson

**Comment by RByers** [comment]
> For ASM.js, is this a full implementation that includes ahead-of-time compilation and type specialized compilation without bailouts? In the past, I think V8 had said they would "recognize" ASM compliant code and make compiler optimizations to make it run faster, but not do AOT etc. Super awesome if it's the full meal deal now!

I'm not sure of the exact details, but I believe it's using the WASM support so will get all the benefits that WASM will get.  @flagxor?

**Comment by flagxor** [comment]
We are preparing an explicit Asm.js validator, which will trigger conversion to WebAssembly internal to v8 and AOT of that code.
This won't have all of the benefits of targeting WebAssembly directly, as asm.js code can't express all of WebAssembly's constructs (64-bit integers for instance).
But this is roughly equivalent to that same feature in Edge (with a different implementation approach).

**Comment by jacobrossi** [comment]
Awesome! Thanks @flagxor for the info. This LGTM then.

**Pull request merged**
