### PR TITLE
Add WebGL2

### PR DESCRIPTION
**Pull request by benaadams**
Ref #188

### CODE REVIEW

**Comment by molant** [comment]
@benaadams that should be "Under Consideration". Can you update it?

**Comment by benaadams** [comment]
Done!

**Comment by molant** [comment]
Thanks! It will take a few minutes to appear in the website

**Comment by benaadams** [comment]
Also fixes #188

**Comment by molant** [comment]
I had to revert the change because there is an issue, you've put "Under Consideration" in the `standardStatus` field instead of `text` under the IE section. Can you fix this and resubmit?
Sorry for not caching this earlier :(

**Comment by molant** [comment]
Nervermind, updating it now. Also it is not an established standard but an editor's draft :)
Should appear shortly

**Comment by benaadams** [comment]
Sorry had a huge merge conflict messed up while resolving :(

Added https://github.com/InternetExplorer/Status.IE/pull/210

**Comment by benaadams** [comment]
Ah you've updated, will close

**Pull request merged**
