### PR TITLE
Brotli compressed data format is now RFC 7932

### PR DESCRIPTION
**Pull request by ghost**
So change the link to https://tools.ietf.org/html/rfc7932. Since Informational RFC is not an Internet standard, I think it's good to call it "de facto standard", rather than "established standard".

By the way, what's the priority of this feature?

### CODE REVIEW

**Comment by szabadka** [comment]
I was about create the exact same PR when I saw this. This fixes #434

**Comment by jacobrossi** [comment]
Thanks. I think it's fair to call this an established standard.  Defacto is typically more things like unspecified -webkit properties and such.

**Comment by ghost** [comment]
@jacobrossi Done!

**Comment by jacobrossi** [comment]
👍

**Comment by kypflug** [comment]
@nextPrime To your question about priority, we're still evaluating this so there's no useful priority to share just yet.

**Comment by ghost** [comment]
@kypflug I see. Thanks!

**Pull request merged**
