### PR TITLE
Tabs to spaces

### PR DESCRIPTION
**Pull request by marian-r**
Fixed inconsistent indentation in CSS and HTML.

### CODE REVIEW

**Comment by dstorey** [comment]
Not to be one of those, but I'd much prefer to use tabs :(

**Comment by jacobrossi** [comment]
Thanks @marian-r, I'm a spaces guy too. Since that seems to be the majority of what we're already using through the site, I think this is the right thing for consistency.

@dstorey - can't believe you're one of _those_ :-p

**Comment by dstorey** [comment]
@jacobrossi we did a straw poll in the office and tabs won. So by W3C style consensus…

**Comment by marian-r** [comment]
Personally, I prefer tabs, but as @jacobrossi mentioned spaces seems to be the major indentaion in this repo, so I used spaces.

**Pull request merged**
