### PR TITLE
Updating CSS Shapes

### PR DESCRIPTION
**Pull request by aarongustafson**
Shapes are a CR now.

### CODE REVIEW

**Comment by aarongustafson** [comment]
Let me know if this is correct. I was not sure if CR are considered "Established standard" or not.

**Comment by jacobrossi** [comment]
Whether we consider CR established is a bit subjective and case by case. In this case, I think it is. So this LGTM.

**Comment by jacobrossi** [comment]
FYI - this will take a bit to appear on the live site. But it should be up soon.

**Comment by junosuarez** [comment]
:+1: I love that this is a thing (public GitHub pull requests by internal team members to status.ie)

**Pull request merged**
